export interface PlayerData {
    id: number,
    name: string,
    playingNumber: number,
    stamina: number,
    ruggedness: number,
    pace: number,
    vision: number,
    positioning: number,
    experience: number,
    heading: number,
    shooting: number,
    shortPassing: number,
    longPassing: number,
    ballControl: number,
    tackling: number,
    goalkeeping: number,
    dribbling: number,
    footedness: string
}