export default {
    CLUB_NUMBER_OF_PLAYERS_AT_START: 11,
    
    PLAYER_SKILL_CEILING_AT_START: 5,
    PLAYER_PROPABILITY_OF_TRAIT: 0.2,
    PLAYER_MIN_AGE_AT_START: 15,
    PLAYER_MAX_AGE_AT_START: 20,

    TIME_GAME_WEEK_IN_REAL_MINUTES: 10
}